### ISSUE TITLE
How to show in .sheet pages? 

### ISSUE THREAD

**Issue by xsown** [JonasGessner/JGProgressHUD-SwiftUI#1]
The ContentView is wrapped with JGProgressHUDPresenter and showing some HUDs, presenting a .sheet page (eg.: some PreferencesView) which is also wrapped with another JGProgressHUDPresenter. Calling show() in the sheet page only shows the HUD in the content view, behind the sheet view itself. (observed from Xcode view hierarchy)
Passing the hudCoordinator from ContentView to .sheet(), instead of wrapping .sheet with JGProgressHUDPresenter, does not help.
Any ideas on this? Or is there another (correct) way to show the HUD? Thanks!
(Falling back to use objc JGProgressHUD now)

**Comment by JonasGessner** [comment]
Please post some minimal code that reproduces the issue!
