### ISSUE TITLE
SPM : Cannot load as it says not a package

### ISSUE THREAD

**Issue by aulimge** [JonasGessner/JGProgressHUD-SwiftUI#4]
![Screenshot 2022-02-24 at 1 30 02 PM](https://user-images.githubusercontent.com/30146547/155463914-38740b72-9968-4756-99ec-5a1da5ba0caf.png)

**Comment by kishorepran** [comment]
@aulimge : You are using the wrong url. Please try this and let me know if it works.
https://github.com/JonasGessner/JGProgressHUD-SwiftUI.git
Note: .git at the end.
